get_and_post/employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'
urlpatterns = [
  path('', views.get_employees, name='get_employees'),
  path('create/', views.create_employee, name='create_employee'),
  path('get_post_employee/', views.get_post_employee, name='get_post_employee'),
]

get_and_post/get_and_post/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('employees.urls', namespace='employees')),
    path('admin/', admin.site.urls),
]

get_and_post/employees/models.py
from django.db import models

class Employee(models.Model):
  last_name = models.CharField(max_length=250)
  first_name = models.CharField(max_length=250)
  salary = models.DecimalField(max_digits=8, decimal_places=2)
  timestamp = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

  def __str__(self):
    return f'{self.last_name} {self.first_name}'

get_and_post/employees/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
  class Meta:
      model = Employee
      fields = ['last_name', 'first_name', 'salary',]

get_and_post/employees/views.py
from django.shortcuts import render, redirect
from .models import Employee
from .forms import EmployeeForm

def get_employees(request):
  context = {
    'employees': Employee.objects.all()
  }
  return render(request, 'employees/employee_list.html', context)

def create_employee(request):
  return render(request, 'employees/employee_form.html')

def get_post_employee(request):
  # si es método POST
  if request.method == 'POST':
    form = EmployeeForm(request.POST)
    if form.is_valid():
      form.save()
      print('Se utilizó el método POST')
      return redirect('employees:get_employees')
  # si es método GET
  elif request.method == 'GET':
    form = EmployeeForm(request.GET)
    if form.is_valid():
      form.save()
      print('Se utilizó el método GET')
      return redirect('employees:get_employees')

get_and_post/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
  <title>GET and POST example</title>
</head>
<body>
  <div class="container">
    <h4>GET and POST example</h4>
    {% block content %}{% endblock %}
  </div>
</body>
</html>

get_and_post/templates/employees/employee_form.html
{% extends 'base.html' %}

{% block content %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">Save employee</span>
      <form action="http://127.0.0.1:8000/get_post_employee/" method="POST">
        {% csrf_token %}
        
        <label for="id_last_name">Last name:</label>
        <input type="text" name="last_name" maxlength="250" required="" id="id_last_name">

        <label for="id_first_name">First name:</label>
        <input type="text" name="first_name" maxlength="250" required="" id="id_first_name">

        <label for="id_salary">Salary:</label>
        <input type="number" name="salary" step="0.01" required="" id="id_salary">

        <button class="btn waves-effect waves-light" type="submit" name="action">
          Submit
          <i class="material-icons right">send</i>
        </button>
      </form>
    </div>
  </div>
{% endblock %}

get_and_post/templates/employees/employee_list.html
{% extends 'base.html' %}

{% block content %}
  <table>
    <thead>
      <tr>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Salary</th>
      </tr>
    </thead>
    
    <tbody>
      {% for employee in employees %}
        <tr>
          <td>{{ employee.last_name }}</td>
          <td>{{ employee.first_name }}</td>
          <td>${{ employee.salary }}</td>
        </tr>
      {% empty %}
        No employees yet
    {% endfor %}
    </tbody>
  </table>
{% endblock %}